import { AuthContextProvider } from "@/contexts/authContext";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Instaclone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
